language: go
sudo: false
install: true

matrix:
  include:
    - os: linux
      go: "1.14.4"
      sudo: true
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: osx
      go: "1.14.4"
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod
script:
  - export os=$(go env GOOS)
  - export arch=$(go env GOARCH)
  - export BUILDTAGS="containers_image_ostree_stub exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp exclude_graphdriver_overlay"
  - curl -sL --retry 5 https://go.kubebuilder.io/dl/2.0.0-beta.0/${os}/${arch} | tar -xz -C /tmp/
  - sudo mv /tmp/kubebuilder_2.0.0-beta.0_${os}_${arch} /usr/local/kubebuilder
  - export PATH=$PATH:/usr/local/kubebuilder/bin
  - export GOBIN=$GOPATH/bin
  - env KUBEBUILDER_CONTROLPLANE_START_TIMEOUT=60s make ci
