apiVersion: migration.openshift.io/v1alpha1
kind: MigCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: migcluster-local
  namespace: mig
spec:
  # [!] Change isHostCluster to 'false' if you want to use a clusterRef and serviceAccountSecretRef
  #     instead of using the detect cluster configuration. Refer to mig-cluster-aws.yaml for an example.
  isHostCluster: true
