apiVersion: v1
kind: Secret
metadata:
  name: sa-token-remote
  namespace: openshift-migration-operator
type: Opaque
data:
  # [!] Change saToken to contain a base64 encoded SA token with cluster-admin 
  #     privileges on the remote cluster.
  #     `oc sa get-token mig -n openshift-migration-operator | base64 -w 0`
  saToken: <your-base64-encoded-aws-sa-token-here>
